BEGIN;

CREATE TABLE projeto (
    ID SERIAL PRIMARY KEY,
    projeto VARCHAR(120) NOT NULL,
    demanda VARCHAR(120),
    localizacao VARCHAR(120),
    cliente VARCHAR(120)
);
CREATE TABLE amostra (
    ID SERIAL PRIMARY KEY,
    amostra VARCHAR(120) NOT NULL,
    idProjeto INT NOT NULL REFERENCES projeto(id) ON DELETE CASCADE,
    furo VARCHAR(120),
    estrutura VARCHAR(120),
    gdms VARCHAR(120),
    cslType VARCHAR(50),
    gamma NUMERIC,
    lambda NUMERIC,
    cslA NUMERIC,
    cslB NUMERIC,
    cslC NUMERIC,
    Mtc NUMERIC,
    Ntc NUMERIC,
    Chi NUMERIC,
    H NUMERIC,
    h0 NUMERIC,
    hy NUMERIC,
    MaterialTested VARCHAR(120),
    JobNumber VARCHAR(120),
    spec_grav_amostra NUMERIC,
    profInicial NUMERIC,
    profFinal NUMERIC,
    coordenada VARCHAR(120),
    local VARCHAR(120),
    tipodeEstrutura VARCHAR(120)
);

CREATE TABLE tipoensaio (
    idtipoensaio SERIAL PRIMARY KEY,
    tipoensaio VARCHAR(40) UNIQUE NOT NULL
);

INSERT INTO tipoensaio (tipoensaio) VALUES 
  ('TriaxialCD'), 
  ('TriaxialCU'), 
  ('Granulometria'), 
  ('Laser'), 
  ('QicPic'),
  ('Limites'), 
  ('Compactacao'), 
  ('DensidadeRelativa'), 
  ('Mineralogia'), 
  ('Quimica'),
  ('CurvaRetencao'), 
  ('AdensamentoEdometrico'), 
  ('AdensamentoIsotropico'),
  ('Permeabilidade'), 
  ('Bender'), 
  ('ColunaRessonante'), 
  ('DSS'), 
  ('CSS');

CREATE TABLE ensaio (
    ID SERIAL PRIMARY KEY,
    idProjeto INT NOT NULL REFERENCES projeto(ID) ON DELETE CASCADE,
    idAmostra INT NOT NULL REFERENCES amostra(ID) ON DELETE CASCADE,
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio)
);

CREATE TABLE cpbender (
    cpbender SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    lab VARCHAR(120),
    testid VARCHAR(120),
    preparationmethod VARCHAR(120),
    testdate DATE,
    spec_grav_cp NUMERIC,
    init_void_ratio NUMERIC,
    type VARCHAR(40),
    psi0 NUMERIC,
    p0 NUMERIC,
    k0 NUMERIC,
    ocr NUMERIC,
    post_consolidation_void_ratio NUMERIC,
    eta_max NUMERIC,
    dmin NUMERIC,
    pc NUMERIC,
    drainage VARCHAR(40),
    strain_rate_pct_hr NUMERIC,
    stresspath VARCHAR(40),
    su_sigma_v0 NUMERIC,
    sr_sigma_v0 NUMERIC,
    steadystate BOOLEAN,
    sigma3final NUMERIC,
    p_final NUMERIC,
    qfinal NUMERIC,
    efinal NUMERIC,
    phi_final NUMERIC,
    remarks TEXT
);

CREATE TABLE cpadensamentoisotropico (
cpisotropico SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    lab VARCHAR(120),
    testid VARCHAR(120),
    preparationmethod VARCHAR(120),
    testdate DATE,
    spec_grav_cp NUMERIC,
    init_void_ratio NUMERIC,
    type VARCHAR(40),
    psi0 NUMERIC,
    p0 NUMERIC,
    k0 NUMERIC,
    ocr NUMERIC,
    post_consolidation_void_ratio NUMERIC,
    eta_max NUMERIC,
    dmin NUMERIC,
    pc NUMERIC,
    drainage VARCHAR(40),
    strain_rate_pct_hr NUMERIC,
    stresspath VARCHAR(40),
    su_sigma_v0 NUMERIC,
    sr_sigma_v0 NUMERIC,
    steadystate BOOLEAN,
    sigma3final NUMERIC,
    p_final NUMERIC,
    qfinal NUMERIC,
    efinal NUMERIC,
    phi_final NUMERIC,
    remarks TEXT
);

CREATE TABLE cpadensamentoedometrico (
cpedo SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    lab VARCHAR(120),
    testid VARCHAR(120),
    preparationmethod VARCHAR(120),
    testdate DATE,
    spec_grav_cp NUMERIC,
    init_void_ratio NUMERIC,
    type VARCHAR(40),
    psi0 NUMERIC,
    p0 NUMERIC,
    k0 NUMERIC,
    ocr NUMERIC,
    post_consolidation_void_ratio NUMERIC,
    eta_max NUMERIC,
    dmin NUMERIC,
    pc NUMERIC,
    drainage VARCHAR(40),
    strain_rate_pct_hr NUMERIC,
    stresspath VARCHAR(40),
    su_sigma_v0 NUMERIC,
    sr_sigma_v0 NUMERIC,
    steadystate BOOLEAN,
    sigma3final NUMERIC,
    p_final NUMERIC,
    qfinal NUMERIC,
    efinal NUMERIC,
    phi_final NUMERIC,
    remarks TEXT
);

CREATE TABLE cpcolunaressoante (
cpcolress SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    lab VARCHAR(120),
    testid VARCHAR(120),
    preparationmethod VARCHAR(120),
    testdate DATE,
    spec_grav_cp NUMERIC,
    init_void_ratio NUMERIC,
    type VARCHAR(40),
    psi0 NUMERIC,
    p0 NUMERIC,
    k0 NUMERIC,
    ocr NUMERIC,
    post_consolidation_void_ratio NUMERIC,
    eta_max NUMERIC,
    dmin NUMERIC,
    pc NUMERIC,
    drainage VARCHAR(40),
    strain_rate_pct_hr NUMERIC,
    stresspath VARCHAR(40),
    su_sigma_v0 NUMERIC,
    sr_sigma_v0 NUMERIC,
    steadystate BOOLEAN,
    sigma3final NUMERIC,
    p_final NUMERIC,
    qfinal NUMERIC,
    efinal NUMERIC,
    phi_final NUMERIC,
    remarks TEXT
);

CREATE TABLE cpdss (
cpdss SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    lab VARCHAR(120),
    testid VARCHAR(120),
    preparationmethod VARCHAR(120),
    testdate DATE,
    spec_grav_cp NUMERIC,
    init_void_ratio NUMERIC,
    type VARCHAR(40),
    psi0 NUMERIC,
    p0 NUMERIC,
    k0 NUMERIC,
    ocr NUMERIC,
    post_consolidation_void_ratio NUMERIC,
    eta_max NUMERIC,
    dmin NUMERIC,
    pc NUMERIC,
    drainage VARCHAR(40),
    strain_rate_pct_hr NUMERIC,
    stresspath VARCHAR(40),
    su_sigma_v0 NUMERIC,
    sr_sigma_v0 NUMERIC,
    steadystate BOOLEAN,
    sigma3final NUMERIC,
    p_final NUMERIC,
    qfinal NUMERIC,
    efinal NUMERIC,
    phi_final NUMERIC,
    remarks TEXT
);

CREATE TABLE cpcss (
cpcss SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    lab VARCHAR(120),
    testid VARCHAR(120),
    preparationmethod VARCHAR(120),
    testdate DATE,
    spec_grav_cp NUMERIC,
    init_void_ratio NUMERIC,
    type VARCHAR(40),
    psi0 NUMERIC,
    p0 NUMERIC,
    k0 NUMERIC,
    ocr NUMERIC,
    post_consolidation_void_ratio NUMERIC,
    eta_max NUMERIC,
    dmin NUMERIC,
    pc NUMERIC,
    drainage VARCHAR(40),
    strain_rate_pct_hr NUMERIC,
    stresspath VARCHAR(40),
    su_sigma_v0 NUMERIC,
    sr_sigma_v0 NUMERIC,
    steadystate BOOLEAN,
    sigma3final NUMERIC,
    p_final NUMERIC,
    qfinal NUMERIC,
    efinal NUMERIC,
    phi_final NUMERIC,
    remarks TEXT
);

CREATE TABLE cpcurvaretencao (
    cpcr SERIAL PRIMARY KEY,
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    testid VARCHAR(120),
    cpcurva INT,
    metodo VARCHAR(60),
    sigmma_prime NUMERIC,
    sigmar_prime NUMERIC,
    p NUMERIC,
    q NUMERIC,
    e NUMERIC,
    preparationmethod VARCHAR(120),
    testdate DATE,
    spec_grav_cp NUMERIC,
    init_void_ratio NUMERIC,
    pressaoar NUMERIC,
    pressaoagua NUMERIC,
    umidadevol NUMERIC,
    densidadeaparenteseca NUMERIC
);

CREATE TABLE cptriaxial (
cptriaxial SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    lab VARCHAR(120),
    testid VARCHAR(120),
    preparationmethod VARCHAR(120),
    testdate DATE,
    spec_grav_cp NUMERIC,
    init_void_ratio NUMERIC,
    type VARCHAR(40),
    psi0 NUMERIC,
    p0 NUMERIC,
    k0 NUMERIC,
    ocr NUMERIC,
    post_consolidation_void_ratio NUMERIC,
    eta_max NUMERIC,
    dmin NUMERIC,
    pc NUMERIC,
    drainage VARCHAR(40),
    strain_rate_pct_hr NUMERIC,
    stresspath VARCHAR(40),
    su_sigma_v0 NUMERIC,
    sr_sigma_v0 NUMERIC,
    steadystate BOOLEAN,
    sigma3final NUMERIC,
    p_final NUMERIC,
    qfinal NUMERIC,
    efinal NUMERIC,
    phi_final NUMERIC,
    remarks TEXT
);

CREATE TABLE cpcomp (
    cpcomp SERIAL PRIMARY KEY,
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    testid VARCHAR(120),
    w NUMERIC,
    densidadeseca NUMERIC
);

CREATE TABLE triaxialcd (
    cptriaxial INT REFERENCES cptriaxial(cptriaxial),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    time_stage NUMERIC,
    ax_strain NUMERIC,
    vol_strain NUMERIC,
    sigmma_prime NUMERIC,
    sigmar_prime NUMERIC,
    p NUMERIC,
    q NUMERIC,
    e NUMERIC,
    eta NUMERIC,
    epq NUMERIC,
    d NUMERIC,
    ec NUMERIC,
    psi NUMERIC,
    PRIMARY KEY (cptriaxial, time_stage)
);

CREATE TABLE triaxialcu (LIKE triaxialcd INCLUDING ALL);

CREATE TABLE granulometria (
    idgl SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    cpbender INT REFERENCES cpbender(cpbender),
    cpedo INT REFERENCES cpadensamentoedometrico(cpedo),
    cpisotropico INT REFERENCES cpadensamentoisotropico(cpisotropico),
    cpcolress INT REFERENCES cpcolunaressoante(cpcolress),
    cpdss INT REFERENCES cpdss(cpdss),
    cpcss INT REFERENCES cpcss(cpcss),
    cpcr INT REFERENCES cpcurvaretencao(cpcr),
    cpcomp INT REFERENCES cpcomp(cpcomp),
    cptriaxial INT REFERENCES cptriaxial(cptriaxial),
    testid VARCHAR(120),
    dispersao VARCHAR(60),
    testdate DATE,
    d5 NUMERIC,
    d10 NUMERIC,
    d15 NUMERIC,
    d20 NUMERIC,
    d30 NUMERIC,
    d50 NUMERIC,
    d60 NUMERIC,
    d85 NUMERIC,
    d90 NUMERIC,
    coloide NUMERIC,
    argila NUMERIC,
    silte NUMERIC,
    areiafina NUMERIC,
    areiamedia NUMERIC,
    areiagrossa NUMERIC,
    pedregulhofino NUMERIC,
    pedregulhomedio NUMERIC,
    pedregulhogrosso NUMERIC,
    n4 NUMERIC,
    n10 NUMERIC,
    n40 NUMERIC,
    n200 NUMERIC,
    n400 NUMERIC,
    cnu NUMERIC,
    cc NUMERIC,
    gs_passante2mm NUMERIC
);

CREATE TABLE qicpic (LIKE granulometria INCLUDING ALL);
ALTER TABLE qicpic RENAME idgl TO idqicpic;

CREATE TABLE limites (
    idlim SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    cpbender INT REFERENCES cpbender(cpbender),
    cpedo INT REFERENCES cpadensamentoedometrico(cpedo),
    cpisotropico INT REFERENCES cpadensamentoisotropico(cpisotropico),
    cpcolress INT REFERENCES cpcolunaressoante(cpcolress),
    cpdss INT REFERENCES cpdss(cpdss),
    cpcss INT REFERENCES cpcss(cpcss),
    cpcr INT REFERENCES cpcurvaretencao(cpcr),
    cpcomp INT REFERENCES cpcomp(cpcomp),
    cptriaxial INT REFERENCES cptriaxial(cptriaxial),
    testid VARCHAR(120),
    ll NUMERIC,
    lp NUMERIC,
    ip NUMERIC,
    descsolo VARCHAR(120),
    corsolo VARCHAR(60)
);

CREATE TABLE desctatiovisual (
    iddtv SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    cpbender INT REFERENCES cpbender(cpbender),
    cpedo INT REFERENCES cpadensamentoedometrico(cpedo),
    cpisotropico INT REFERENCES cpadensamentoisotropico(cpisotropico),
    cpcolress INT REFERENCES cpcolunaressoante(cpcolress),
    cpdss INT REFERENCES cpdss(cpdss),
    cpcss INT REFERENCES cpcss(cpcss),
    cpcr INT REFERENCES cpcurvaretencao(cpcr),
    cpcomp INT REFERENCES cpcomp(cpcomp),
    cptriaxial INT REFERENCES cptriaxial(cptriaxial),
    testid VARCHAR(120),
    descr TEXT,
    cor VARCHAR(60),
    tipo VARCHAR(60),
    classunificada VARCHAR(60),
    classrodoviaria VARCHAR(60)
);

CREATE TABLE compactacao (
    idcomp SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    cpbender INT REFERENCES cpbender(cpbender),
    cpedo INT REFERENCES cpadensamentoedometrico(cpedo),
    cpisotropico INT REFERENCES cpadensamentoisotropico(cpisotropico),
    cpcolress INT REFERENCES cpcolunaressoante(cpcolress),
    cpdss INT REFERENCES cpdss(cpdss),
    cpcss INT REFERENCES cpcss(cpcss),
    cpcr INT REFERENCES cpcurvaretencao(cpcr),
    cpcomp INT REFERENCES cpcomp(cpcomp),
    cptriaxial INT REFERENCES cptriaxial(cptriaxial),
    testid VARCHAR(120),
    wotima NUMERIC,
    densidadesecamax NUMERIC,
    tipo VARCHAR(40)
);

CREATE TABLE densidaderelativa (
    iddr SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    cpbender INT REFERENCES cpbender(cpbender),
    cpedo INT REFERENCES cpadensamentoedometrico(cpedo),
    cpisotropico INT REFERENCES cpadensamentoisotropico(cpisotropico),
    cpcolress INT REFERENCES cpcolunaressoante(cpcolress),
    cpdss INT REFERENCES cpdss(cpdss),
    cpcss INT REFERENCES cpcss(cpcss),
    cpcr INT REFERENCES cpcurvaretencao(cpcr),
    cpcomp INT REFERENCES cpcomp(cpcomp),
    cptriaxial INT REFERENCES cptriaxial(cptriaxial),
    testid VARCHAR(120),
    emax NUMERIC,
    emin NUMERIC
);

CREATE TABLE mineralogia (
    idm SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    cpbender INT REFERENCES cpbender(cpbender),
    cpedo INT REFERENCES cpadensamentoedometrico(cpedo),
    cpisotropico INT REFERENCES cpadensamentoisotropico(cpisotropico),
    cpcolress INT REFERENCES cpcolunaressoante(cpcolress),
    cpdss INT REFERENCES cpdss(cpdss),
    cpcss INT REFERENCES cpcss(cpcss),
    cpcr INT REFERENCES cpcurvaretencao(cpcr),
    cpcomp INT REFERENCES cpcomp(cpcomp),
    cptriaxial INT REFERENCES cptriaxial(cptriaxial),
    testid VARCHAR(120),
    faixagranulometrica VARCHAR(60),
    tecnica VARCHAR(60),
    quartzo NUMERIC,
    feldspatos NUMERIC,
    biotita NUMERIC,
    muscovita NUMERIC,
    clorita NUMERIC,
    caulinita NUMERIC,
    oxidosfe NUMERIC,
    oxidosmn NUMERIC,
    oxidosti NUMERIC,
    gibbsita NUMERIC,
    outrasfases NUMERIC
);

CREATE TABLE quimica (
    idquimica SERIAL PRIMARY KEY,
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    cpbender INT REFERENCES cpbender(cpbender),
    cpedo INT REFERENCES cpadensamentoedometrico(cpedo),
    cpisotropico INT REFERENCES cpadensamentoisotropico(cpisotropico),
    cpcolress INT REFERENCES cpcolunaressoante(cpcolress),
    cpdss INT REFERENCES cpdss(cpdss),
    cpcss INT REFERENCES cpcss(cpcss),
    cpcr INT REFERENCES cpcurvaretencao(cpcr),
    cpcomp INT REFERENCES cpcomp(cpcomp),
    cptriaxial INT REFERENCES cptriaxial(cptriaxial),
    testid VARCHAR(120),
    microns NUMERIC,
    retsimples NUMERIC,
    retacumulado NUMERIC,
    fe NUMERIC,
    sio2 NUMERIC,
    p NUMERIC,
    al2o3 NUMERIC,
    mn NUMERIC,
    tio2 NUMERIC,
    cao NUMERIC,
    mgo NUMERIC,
    ppc NUMERIC,
    fq NUMERIC
);

CREATE TABLE permeabilidade (
    idperm SERIAL PRIMARY KEY,
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    cpbender INT REFERENCES cpbender(cpbender),
    cpedo INT REFERENCES cpadensamentoedometrico(cpedo),
    cpisotropico INT REFERENCES cpadensamentoisotropico(cpisotropico),
    cpcolress INT REFERENCES cpcolunaressoante(cpcolress),
    cpdss INT REFERENCES cpdss(cpdss),
    cpcss INT REFERENCES cpcss(cpcss),
    cpcr INT REFERENCES cpcurvaretencao(cpcr),
    cpcomp INT REFERENCES cpcomp(cpcomp),
    cptriaxial INT REFERENCES cptriaxial(cptriaxial),
    testid VARCHAR(120),
    sigmma_prime NUMERIC,
    sigmar_prime NUMERIC,
    p NUMERIC,
    q NUMERIC,
    e NUMERIC,
    k NUMERIC
);

CREATE TABLE curvaretencao (
    cpcr INT PRIMARY KEY REFERENCES cpcurvaretencao(cpcr),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    testid VARCHAR(120),
    tetas NUMERIC,
    tetar NUMERIC
);

CREATE TABLE adensamentoedometrico (
    cpedo INT PRIMARY KEY REFERENCES cpadensamentoedometrico(cpedo),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    testid VARCHAR(120),
    time_stage NUMERIC,
    ax_strain NUMERIC,
    vol_strain NUMERIC,
    sigmma_prime NUMERIC,
    sigmar_prime NUMERIC,
    p NUMERIC,
    q NUMERIC,
    e NUMERIC,
    eta NUMERIC,
    epq NUMERIC,
    d NUMERIC,
    ec NUMERIC,
    psi NUMERIC
);

CREATE TABLE adensamentoisotropico (
    cpisotropico INT PRIMARY KEY REFERENCES cpadensamentoisotropico(cpisotropico),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    testid VARCHAR(120),
    time_stage NUMERIC,
    ax_strain NUMERIC,
    vol_strain NUMERIC,
    sigmma_prime NUMERIC,
    sigmar_prime NUMERIC,
    p NUMERIC,
    q NUMERIC,
    e NUMERIC,
    eta NUMERIC,
    epq NUMERIC,
    d NUMERIC,
    ec NUMERIC,
    psi NUMERIC
);

CREATE TABLE bender (
    cpbender INT PRIMARY KEY REFERENCES cpbender(cpbender),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    testid VARCHAR(120),
    time_stage NUMERIC,
    ax_strain NUMERIC,
    vol_strain NUMERIC,
    sigmma_prime NUMERIC,
    sigmar_prime NUMERIC,
    p NUMERIC,
    q NUMERIC,
    e NUMERIC,
    eta NUMERIC,
    epq NUMERIC,
    d NUMERIC,
    ec NUMERIC,
    psi NUMERIC
);

CREATE TABLE colunaressoante (
    cpcolress INT PRIMARY KEY REFERENCES cpcolunaressoante(cpcolress),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    testid VARCHAR(120),
    time_stage NUMERIC,
    ax_strain NUMERIC,
    vol_strain NUMERIC,
    sigmma_prime NUMERIC,
    sigmar_prime NUMERIC,
    p NUMERIC,
    q NUMERIC,
    e NUMERIC,
    eta NUMERIC,
    epq NUMERIC,
    d NUMERIC,
    ec NUMERIC,
    psi NUMERIC
);

CREATE TABLE dss (
    cpdss INT PRIMARY KEY REFERENCES cpdss(cpdss),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    testid VARCHAR(120),
    time_stage NUMERIC,
    ax_strain NUMERIC,
    vol_strain NUMERIC,
    sigmma_prime NUMERIC,
    sigmar_prime NUMERIC,
    p NUMERIC,
    q NUMERIC,
    e NUMERIC,
    eta NUMERIC,
    epq NUMERIC,
    d NUMERIC,
    ec NUMERIC,
    psi NUMERIC
);

CREATE TABLE css (
    cpcss INT PRIMARY KEY REFERENCES cpcss(cpcss),
    idensaio INT NOT NULL REFERENCES ensaio(ID),
    idprojeto INT NOT NULL REFERENCES projeto(ID),
    idamostra INT NOT NULL REFERENCES amostra(ID),
    idtipoensaio INT NOT NULL REFERENCES tipoensaio(idtipoensaio),
    testid VARCHAR(120),
    time_stage NUMERIC,
    ax_strain NUMERIC,
    vol_strain NUMERIC,
    sigmma_prime NUMERIC,
    sigmar_prime NUMERIC,
    p NUMERIC,
    q NUMERIC,
    e NUMERIC,
    eta NUMERIC,
    epq NUMERIC,
    d NUMERIC,
    ec NUMERIC,
    psi NUMERIC
);

COMMIT;